version: 2
publish: &publish
  working_directory: ~/msa-mobile
  docker:
    - image: circleci/node:10.17.0

  steps:
    - checkout

    - run: 
          name: "Setup custom environment variables"
          command: |
            echo 'BACKEND_URL='${BACKEND_URL} > .env
            echo 'IS_STORYBOOK_ENABLED=false' >> .env
            echo 'PUSHER_APP_ID='${PUSHER_APP_ID} >> .env
            echo 'PUSHER_APP_KEY='${PUSHER_APP_KEY} >> .env
            echo 'PUSHER_APP_SECRET='${PUSHER_APP_SECRET} >> .env
            echo 'CLUSTER='${CLUSTER} >> .env
            echo 'PUSHER_MSA_MESSAGE_CHANNEL='${PUSHER_MSA_MESSAGE_CHANNEL} >> .env
            cat .env

    - run:
        name: Installing exp
        command: yarn global add expo-cli

    - run:
        name: Installing dependencies
        command: yarn install

    - run:
        name: Deploying to Expo
        command: |
            export PATH="$PATH:$( yarn global bin )"
            expo login --username ${EXPO_USER_NAME} --password ${EXPO_PASSWORD}
            expo optimize
            expo publish --non-interactive

    - run:
       name: Build Android version
       command:  |
           export PATH="$PATH:$( yarn global bin )"
           expo push:android:upload --api-key ${FIREBASE_SERVER_KEY}
           expo build:android --non-interactive

jobs:
  publish_to_expo_dev:
    environment:
      EXPO_RELEASE_CHANNEL: dev
    <<: *publish

  publish_to_expo_prod:
    environment:
      EXPO_RELEASE_CHANNEL: default
    <<: *publish

workflows:
  version: 2
  my_app:
    jobs:
      - publish_to_expo_dev:
          filters:
            branches:
              only: develop
      - publish_to_expo_prod:
          filters:
            branches:
              only: master